# Change these first
owner: NFTfi-Genesis # Your GitHub organization or username, where this repository lives
repo: nftfi-services-status # The name of this repository

sites:
  - name: NFTfi
    url: https://nftfi.com
  - name: dApp
    url: https://app.nftfi.com
  - name: API
    url: https://api.nftfi.com
  - name: SDK API /listings
    url: https://sdk-api.nftfi.com/listings
    method: OPTIONS
    headers:
      - "X-API-KEY: $SDK_API_KEY"
    expectedStatusCodes:
      - 204
  - name: SDK API /loans
    url: https://sdk-api.nftfi.com/loans
    method: OPTIONS
    headers:
      - "X-API-KEY: $SDK_API_KEY"
    expectedStatusCodes:
      - 204
  - name: SDK API /offers
    url: https://sdk-api.nftfi.com/offers
    method: OPTIONS
    headers:
      - "X-API-KEY: $SDK_API_KEY"
    expectedStatusCodes:
      - 204
  - name: SDK API /authorization/token
    url: https://sdk-api.nftfi.com/authorization/token
    method: OPTIONS
    headers:
      - "X-API-KEY: $SDK_API_KEY"
    expectedStatusCodes:
      - 204
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /nftfi-services-status
  logoUrl: https://images.ctfassets.net/21yktilggb3f/4stgUPiFxcurCYUf40mfQx/755520e8150318e1b1de08826b9982bb/nftfi-logo.svg
  name: NFTfi status page
  introTitle: "**NFTfi** status page"
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/NFTfi-Genesis/nftfi-services-status).
  navbar:
    - title: GitHub Monitor Repo
      href: https://github.com/$OWNER/$REPO
  theme: dark
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
